### ISSUE TITLE
Concern about potentially private data in SML Messages

### ISSUE THREAD

**Issue by danielr1996** [devZer0/libsml-testing#10]
Hello,

I would be happy to submit some test data for the Iskra MT681. However I'm very new to this topic and having watched multiple Youtube Videos on this without no exception everyone censored their server id and public key. Therefore I assumed that this data should be private and allows conclusions about my person. But here this data is freely available, what are the public key and server id really for and what could someone do with this data if publicly available?

**Comment by devZer0** [comment]
hello, thanks for bringing this up. 

i asked this myself several times and did some search on the web, but i don't see the point why this data would allow any conclusions about the smartmeter owners, nor do i see the point how this could be abused.  it's just a device number and a public key, which is (as it tells) a >public< key. 

we could elaborate a methode to obfuscate this data, but i'm not sure if it's worth the effort. 

could you point me to the youtube videos where people censor their sml data ?

would you mind bringing this up for discussion at https://demo.volkszaehler.org/mailman/listinfo/volkszaehler-users mailing list ? 

i think that's the right place to discuss that.

**Comment by danielr1996** [comment]
Moved discussion to mailing list

**Comment by devZer0** [comment]
is there something wrong with the mailing list archving at https://demo.volkszaehler.org/mailman/listinfo/volkszaehler-users ?

i see no october posts

**Comment by devZer0** [comment]
@danielr1996 , did you send the question to volkszähler mailinglist ? what was the reply ?

**Comment by danielr1996** [comment]
> @danielr1996 , did you send the question to volkszähler mailinglist ? what was the reply ?

As you stated there might have been a problem with the mailing list and my message might have been lost. But it seems that you already have forwarded my message, thanks for that. As it seems it should really be no problem to share the server id and public key.

**Comment by devZer0** [comment]
thanks for feedback
