### ISSUE TITLE
EasyMeter example doesn't work

### ISSUE THREAD

**Issue by fkohlgrueber** [devZer0/libsml-testing#11]
Hi,

I'm working on an sml implementation written in Rust and this repository has been of great help while debugging.

I'm now at a point where almost all dumps can be parsed. The only one that doesn't work is the EasyMeter dump. Trying to read it with the latest libsml also doesn't seem to work:

```bash
felix@the-machine:~/tmp/libsml/examples$ cat ~/tmp/libsml-testing/EasyMeter_Q3A_A1064V1009.bin | ./sml_server -
libsml: error: unrecognized sequence
```

Looking at the dump, I can't see any end sequences, only start sequences (`1B1B1B1B01010101`). Am I missing something or is the dump corrupt?

Thanks in advance!

**Comment by devZer0** [comment]
yes, you are right, apparently the file is corrupted or invalid. i will now check every file before merging. 

@lapawa, can you check for this ?

**Comment by lapawa** [comment]
Kindly ask to merge #12 with a fresh created dump from EasyMeter.

**Comment by foorschtbar** [comment]
I can confirm that the two files from the Q3A are corrupted. The files from #12 works. 

@devZer0 Please accept the PR.
